import type { Metadata } from "next";
import { Inter, Outfit } from "next/font/google";
import "./globals.css";
import Providers from "./Providers";
import { Toaster } from "react-hot-toast"; // ✅ Import Toaster

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit",
  display: "swap",
});

export const metadata: Metadata = {
  title: "FOODIFY - Wajahat Kamal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${outfit.variable} antialiased bg-[#0B111E] text-white`}
      >
        <Providers>
          {children}
          {/* ✅ React Hot Toast */}
          <Toaster
            position="top-right"
            toastOptions={{
              duration: 3000,
              style: {
                background: "#141B2E",
                color: "#fff",
                border: "1px solid #222",
              },
              success: {
                iconTheme: { primary: "#22c55e", secondary: "#0B111E" },
              },
              error: {
                iconTheme: { primary: "#ef4444", secondary: "#0B111E" },
              },
            }}
          />
        </Providers>
      </body>
    </html>
  );
}
